---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "..serviceAccountName" . }}
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["workflow-deploy.ngerakines.me"]
  resources: ["workflows"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apiextensions.k8s.io"] 
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "..serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "..serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "..serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
