---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow-deployment
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["workflow-deploy.ngerakines.me"]
  resources: ["workflows"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apiextensions.k8s.io"] 
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workflow-deployment
subjects:
- kind: ServiceAccount
  name: workflow-deployment
  namespace: workflow-deployment
roleRef:
  kind: ClusterRole
  name: workflow-deployment
  apiGroup: rbac.authorization.k8s.io