apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: statsd-debug
  namespace: kube-system
  labels:
    k8s-app: statsd-debug
spec:
  selector:
    matchLabels:
      name: statsd-debug
  template:
    metadata:
      labels:
        name: statsd-debug
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: statsd-debug
        image: dasch/statsd-debug
        ports:
        - hostPort: 8125
          containerPort: 80
          name: statsd
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: statsd-debug
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: statsd
    port: 8125
    protocol: UDP
    targetPort: 8125
  selector:
    name: statsd-debug
  sessionAffinity: None
  type: ClusterIP
