---
apiVersion: workflow-deploy.ngerakines.me/v1alpha
kind: Workflow
metadata:
  name: foo
spec:
  version: "1.0.0-3"
  debounce: 90
  namespaces: ["foo"]
  supression:
  - "2023-05-02T10:44:59.218375-04:00"
  - "2023-05-02T10:44:58.218375-04:00 2023-05-02T10:44:59.218375-04:00"
  steps:
  - actions:
    - action: update_deployment
      targets:
      - resource: Deployment
        name: foo
        containers: ["app"]
