---
apiVersion: workflow-deploy.ngerakines.me/v1alpha
kind: Workflow
metadata:
  name: foo
spec:
  version: "1.0.0-1"
  debounce: 90
  namespaces: ["foo"]
  supression:
  - "2023-05-02T14:00:00.000000-04:00"
  - "2023-05-05T19:00:0-04:00 2023-05-09T07:00:00-04:00"
  steps:
  - actions:
    - action: update_deployment
      targets:
      - resource: Deployment
        name: foo
        containers: ["app"]
