name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ngerakines/workflow-deploy
            ghcr.io/ngerakines/workflow-deploy
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
